#!/bin/bash

SOURCE_PLAUSIBLE_ENV_PATH=$APP_PATH/source/deploy/envs/plausible.env
SOURCE_POSTGRES_ENV_PATH=$APP_PATH/source/deploy/envs/postgres.env
FILLED_PLAUSIBLE_ENV_PATH=$APP_PATH/envs/plausible.env
FILLED_POSTGRES_ENV_PATH=$APP_PATH/envs/postgres.env

rm $SOURCE_PLAUSIBLE_ENV_PATH
rm $SOURCE_POSTGRES_ENV_PATH

ln -s $FILLED_PLAUSIBLE_ENV_PATH $SOURCE_PLAUSIBLE_ENV_PATH
ln -s $FILLED_POSTGRES_ENV_PATH $SOURCE_POSTGRES_ENV_PATH
