name: evil-cards-dev

services:
  keydb:
    extends:
      file: docker-compose.common.yml
      service: keydb
    restart: "no"

  server:
    extends:
      file: docker-compose.common.yml
      service: server
    restart: "no"
    image: tilt/server
    depends_on:
      keydb:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - KEYDB_URL=redis://keydb:6379
      - CORS_ORIGIN=*

  load-balancer:
    extends:
      file: docker-compose.common.yml
      service: load-balancer
    restart: "no"
    image: tilt/load-balancer
    depends_on:
      keydb:
        condition: service_healthy
      server:
        condition: service_healthy
    ports:
      - 1337:1337
    environment:
      - KEYDB_URL=redis://keydb:6379
      - SITE_DOMAIN=localhost
      - CORS_ORIGIN=*
      - WS_PROTOCOL=ws
      - INITIAL_AVAILABLE_SERVERS=1

  client:
    image: tilt/client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_WS_HOST=ws://server:8000
      - NEXT_PUBLIC_SITE_HOST=http://localhost:3000
