name: evil-cards-dev

services:
  keydb:
    extends:
      file: docker-compose.common.yml
      service: keydb
    restart: "no"

  server:
    extends:
      file: docker-compose.common.yml
      service: server
    restart: "no"
    image: tilt/server
    depends_on:
      keydb:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - KEYDB_URL=redis://keydb:6379
      - CORS_ORIGIN=*
    labels:
      - balancer-target=server

  load-balancer:
    extends:
      file: docker-compose.common.yml
      service: load-balancer
    image: tilt/load-balancer
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      server:
        condition: service_started
      keydb:
        condition: service_healthy
    ports:
      - 1337:1337
    environment:
      - KEYDB_URL=redis://keydb:6379
      - CORS_ORIGIN=*
      - PATTERN=ws://localhost:8000
      - TARGET=server

  client:
    image: tilt/client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BALANCER_PATH=http://localhost:1337
      - NEXT_PUBLIC_SITE_HOST=http://localhost:3000
