name: Start services

on:
  workflow_dispatch:
    inputs:
      deploy-env:
        description: Environment
        type: choice
        options:
          - stage
          - prod

jobs:
  start-services:
    runs-on: ubuntu-latest
    name: Start services

    steps:
      - name: Start services
        uses: appleboy/ssh-action@v0.1.7
        env:
          REPOSITORY: ${{ github.repository }}
          APP_PATH: /app
          SOURCE_DIR: source-services-start-${{ inputs.deploy-env }}
          DEPLOY_ENV: ${{ inputs.deploy-env }}
          VERSION: latest
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          envs: REPOSITORY,APP_PATH,SOURCE_DIR,DEPLOY_ENV,VERSION
          script: |
            git clone --single-branch --branch ${{ github.ref_name }} https://github.com/$REPOSITORY.git $APP_PATH/$SOURCE_DIR
            $APP_PATH/$SOURCE_DIR/deploy/scripts/start-services.sh
